name: cadavis
description: "Cadaver Detection System"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  
  # LOCALIZATION
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # DATABASE
  sqflite: ^2.3.0
  path: ^1.9.0

  # EXPORT EXCEL
  excel: ^4.0.3
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  open_file: ^3.3.2

  # DATE & DEVICE INFO
  intl: 0.20.2
  device_info_plus: ^10.1.0

  # LOGIN
  shared_preferences: ^2.2.2

  # CHART
  fl_chart: ^0.66.2

  # IMAGE PICKER
  image_picker: ^1.0.7

  geolocator: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # APP ICON
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo_cadavis.jpg
    - assets/images.jpg


# ============================
# CONFIG ICON APK
# ============================
flutter_icons:
  android: true
  ios: true
  image_path: assets/logo_cadavis.jpg